// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for drizzle.__drizzle_migrations */
export type DrizzleMigrationsId = number & { __brand: 'DrizzleMigrationsId' };

/** Represents the table drizzle.__drizzle_migrations */
export default interface DrizzleMigrationsTable {
  id: ColumnType<DrizzleMigrationsId, DrizzleMigrationsId | undefined, DrizzleMigrationsId>;

  hash: ColumnType<string, string, string>;

  created_at: ColumnType<string | null, string | null, string | null>;
}

export type DrizzleMigrations = Selectable<DrizzleMigrationsTable>;

export type NewDrizzleMigrations = Insertable<DrizzleMigrationsTable>;

export type DrizzleMigrationsUpdate = Updateable<DrizzleMigrationsTable>;
