// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as DrizzleMigrationsTable } from './DrizzleMigrations';

export default interface DrizzleSchema {
  __drizzle_migrations: DrizzleMigrationsTable;
}
