// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as VaultSchema } from './vault/VaultSchema';
import type { default as AuthSchema } from './auth/AuthSchema';
import type { default as RealtimeSchema } from './realtime/RealtimeSchema';
import type { default as DrizzleSchema } from './drizzle/DrizzleSchema';
import type { default as PublicSchema } from './public/PublicSchema';
import type { default as StorageSchema } from './storage/StorageSchema';

type Database = VaultSchema & AuthSchema & RealtimeSchema & DrizzleSchema & PublicSchema & StorageSchema;

export default Database;
