// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.dropdownOptions */
export type DropdownOptionsId = number & { __brand: 'DropdownOptionsId' };

/** Represents the table public.dropdownOptions */
export default interface DropdownOptionsTable {
  id: ColumnType<DropdownOptionsId, DropdownOptionsId | undefined, DropdownOptionsId>;

  group: ColumnType<string, string, string>;

  value: ColumnType<string, string, string>;

  label: ColumnType<string, string, string>;
}

export type DropdownOptions = Selectable<DropdownOptionsTable>;

export type NewDropdownOptions = Insertable<DropdownOptionsTable>;

export type DropdownOptionsUpdate = Updateable<DropdownOptionsTable>;
