// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { HassEntityId } from './HassEntity';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.hassService */
export type HassServiceId = number & { __brand: 'HassServiceId' };

/** Represents the table public.hassService */
export default interface HassServiceTable {
  id: ColumnType<HassServiceId, HassServiceId | undefined, HassServiceId>;

  entity: ColumnType<HassEntityId, HassEntityId, HassEntityId>;

  domain: ColumnType<string, string, string>;

  service: ColumnType<string, string, string>;

  target: ColumnType<string, string, string>;

  userId: ColumnType<string, string, string>;
}

export type HassService = Selectable<HassServiceTable>;

export type NewHassService = Insertable<HassServiceTable>;

export type HassServiceUpdate = Updateable<HassServiceTable>;
