// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.hassEntity */
export type HassEntityId = number & { __brand: 'HassEntityId' };

/** Represents the table public.hassEntity */
export default interface HassEntityTable {
  id: ColumnType<HassEntityId, HassEntityId | undefined, HassEntityId>;

  entityId: ColumnType<string, string, string>;

  type: ColumnType<string, string, string>;

  icon: ColumnType<string | null, string | null, string | null>;

  lock: ColumnType<boolean | null, boolean | null, boolean | null>;

  name: ColumnType<string | null, string | null, string | null>;

  state: ColumnType<string | null, string | null, string | null>;

  userId: ColumnType<string, string, string>;

  cardX: ColumnType<string | null, string | null, string | null>;

  cardY: ColumnType<string | null, string | null, string | null>;

  cardRows: ColumnType<string | null, string | null, string | null>;

  cardCols: ColumnType<string | null, string | null, string | null>;
}

export type HassEntity = Selectable<HassEntityTable>;

export type NewHassEntity = Insertable<HassEntityTable>;

export type HassEntityUpdate = Updateable<HassEntityTable>;
