// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { HassEntityId } from './HassEntity';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.hassStateOptions */
export type HassStateOptionsId = number & { __brand: 'HassStateOptionsId' };

/** Represents the table public.hassStateOptions */
export default interface HassStateOptionsTable {
  id: ColumnType<HassStateOptionsId, HassStateOptionsId | undefined, HassStateOptionsId>;

  entity: ColumnType<HassEntityId, HassEntityId, HassEntityId>;

  beforeString: ColumnType<string | null, string | null, string | null>;

  afterString: ColumnType<string | null, string | null, string | null>;

  warningExpression: ColumnType<string | null, string | null, string | null>;

  dangerExpression: ColumnType<string | null, string | null, string | null>;

  round: ColumnType<boolean | null, boolean | null, boolean | null>;

  track: ColumnType<boolean | null, boolean | null, boolean | null>;

  displayGraph: ColumnType<boolean | null, boolean | null, boolean | null>;

  userId: ColumnType<string, string, string>;
}

export type HassStateOptions = Selectable<HassStateOptionsTable>;

export type NewHassStateOptions = Insertable<HassStateOptionsTable>;

export type HassStateOptionsUpdate = Updateable<HassStateOptionsTable>;
