// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as KyselyMigrationTable } from './KyselyMigration';
import type { default as KyselyMigrationLockTable } from './KyselyMigrationLock';
import type { default as HassEntityTable } from './HassEntity';
import type { default as HassServiceTable } from './HassService';
import type { default as HassStateOptionsTable } from './HassStateOptions';
import type { default as DropdownOptionsTable } from './DropdownOptions';

export default interface PublicSchema {
  kysely_migration: KyselyMigrationTable;

  kysely_migration_lock: KyselyMigrationLockTable;

  hassEntity: HassEntityTable;

  hassService: HassServiceTable;

  hassStateOptions: HassStateOptionsTable;

  dropdownOptions: DropdownOptionsTable;
}
