// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as AuditLogEntriesTable } from './AuditLogEntries';
import type { default as FlowStateTable } from './FlowState';
import type { default as IdentitiesTable } from './Identities';
import type { default as InstancesTable } from './Instances';
import type { default as MfaAmrClaimsTable } from './MfaAmrClaims';
import type { default as MfaChallengesTable } from './MfaChallenges';
import type { default as MfaFactorsTable } from './MfaFactors';
import type { default as OneTimeTokensTable } from './OneTimeTokens';
import type { default as RefreshTokensTable } from './RefreshTokens';
import type { default as SamlProvidersTable } from './SamlProviders';
import type { default as SamlRelayStatesTable } from './SamlRelayStates';
import type { default as SchemaMigrationsTable } from './SchemaMigrations';
import type { default as SessionsTable } from './Sessions';
import type { default as SsoDomainsTable } from './SsoDomains';
import type { default as SsoProvidersTable } from './SsoProviders';
import type { default as UsersTable } from './Users';

export default interface AuthSchema {
  audit_log_entries: AuditLogEntriesTable;

  flow_state: FlowStateTable;

  identities: IdentitiesTable;

  instances: InstancesTable;

  mfa_amr_claims: MfaAmrClaimsTable;

  mfa_challenges: MfaChallengesTable;

  mfa_factors: MfaFactorsTable;

  one_time_tokens: OneTimeTokensTable;

  refresh_tokens: RefreshTokensTable;

  saml_providers: SamlProvidersTable;

  saml_relay_states: SamlRelayStatesTable;

  schema_migrations: SchemaMigrationsTable;

  sessions: SessionsTable;

  sso_domains: SsoDomainsTable;

  sso_providers: SsoProvidersTable;

  users: UsersTable;
}
